### PR TITLE
Update to v0.2.1

### PR DESCRIPTION
**Pull request by TShimko126**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

# Changes
- Updated to PyPI version 0.2.1

### CODE REVIEW

**Comment by TShimko126** [comment]
@conda-forge-admin please rerender

**Comment by TShimko126** [comment]
@conda-forge-admin, please ping team

Hi conda-forge team - I am listed as the maintainer of this feedstock, but do not have write permissions to the repo to merge this PR. Thanks in advance for your help!

**Comment by TShimko126** [comment]
@conda-forge-admin, please ping @conda-forge/core

Hi core team - I missed the email invitation to join the conda-forge org (necessary to merge this PR) and it has now been >7 days so the invite expired. Would it be possible to have the invitation resent? Apologies for the inconvenience and thanks in advance!

**Comment by dopplershift** [comment]
In theory #4 should have sent you a new invite.

**Comment by TShimko126** [comment]
@dopplershift Confirmed! I was able to join the org. Thank you!

**Pull request merged**
